// Generated by gencpp from file ccmslam/ServiceSaveMap.msg
// DO NOT EDIT!


#ifndef CCMSLAM_MESSAGE_SERVICESAVEMAP_H
#define CCMSLAM_MESSAGE_SERVICESAVEMAP_H

#include <ros/service_traits.h>


#include <ccmslam/ServiceSaveMapRequest.h>
#include <ccmslam/ServiceSaveMapResponse.h>


namespace ccmslam
{

struct ServiceSaveMap
{

typedef ServiceSaveMapRequest Request;
typedef ServiceSaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServiceSaveMap
} // namespace ccmslam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ccmslam::ServiceSaveMap > {
  static const char* value()
  {
    return "33771723490df6e718df42a37edc4c0b";
  }

  static const char* value(const ::ccmslam::ServiceSaveMap&) { return value(); }
};

template<>
struct DataType< ::ccmslam::ServiceSaveMap > {
  static const char* value()
  {
    return "ccmslam/ServiceSaveMap";
  }

  static const char* value(const ::ccmslam::ServiceSaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::ccmslam::ServiceSaveMapRequest> should match
// service_traits::MD5Sum< ::ccmslam::ServiceSaveMap >
template<>
struct MD5Sum< ::ccmslam::ServiceSaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ccmslam::ServiceSaveMap >::value();
  }
  static const char* value(const ::ccmslam::ServiceSaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ccmslam::ServiceSaveMapRequest> should match
// service_traits::DataType< ::ccmslam::ServiceSaveMap >
template<>
struct DataType< ::ccmslam::ServiceSaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::ccmslam::ServiceSaveMap >::value();
  }
  static const char* value(const ::ccmslam::ServiceSaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ccmslam::ServiceSaveMapResponse> should match
// service_traits::MD5Sum< ::ccmslam::ServiceSaveMap >
template<>
struct MD5Sum< ::ccmslam::ServiceSaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ccmslam::ServiceSaveMap >::value();
  }
  static const char* value(const ::ccmslam::ServiceSaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ccmslam::ServiceSaveMapResponse> should match
// service_traits::DataType< ::ccmslam::ServiceSaveMap >
template<>
struct DataType< ::ccmslam::ServiceSaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::ccmslam::ServiceSaveMap >::value();
  }
  static const char* value(const ::ccmslam::ServiceSaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CCMSLAM_MESSAGE_SERVICESAVEMAP_H
