// Generated by gencpp from file ccmslam/ServiceSaveMapResponse.msg
// DO NOT EDIT!


#ifndef CCMSLAM_MESSAGE_SERVICESAVEMAPRESPONSE_H
#define CCMSLAM_MESSAGE_SERVICESAVEMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ccmslam
{
template <class ContainerAllocator>
struct ServiceSaveMapResponse_
{
  typedef ServiceSaveMapResponse_<ContainerAllocator> Type;

  ServiceSaveMapResponse_()
    : retval(0)  {
    }
  ServiceSaveMapResponse_(const ContainerAllocator& _alloc)
    : retval(0)  {
  (void)_alloc;
    }



   typedef int64_t _retval_type;
  _retval_type retval;





  typedef boost::shared_ptr< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceSaveMapResponse_

typedef ::ccmslam::ServiceSaveMapResponse_<std::allocator<void> > ServiceSaveMapResponse;

typedef boost::shared_ptr< ::ccmslam::ServiceSaveMapResponse > ServiceSaveMapResponsePtr;
typedef boost::shared_ptr< ::ccmslam::ServiceSaveMapResponse const> ServiceSaveMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator1> & lhs, const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.retval == rhs.retval;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator1> & lhs, const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ccmslam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e0d9a28e8d24ecfb532e7cf938e3f86";
  }

  static const char* value(const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e0d9a28e8d24ecfULL;
  static const uint64_t static_value2 = 0xb532e7cf938e3f86ULL;
};

template<class ContainerAllocator>
struct DataType< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccmslam/ServiceSaveMapResponse";
  }

  static const char* value(const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 retval\n"
"\n"
;
  }

  static const char* value(const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.retval);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceSaveMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ccmslam::ServiceSaveMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "retval: ";
    Printer<int64_t>::stream(s, indent + "  ", v.retval);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCMSLAM_MESSAGE_SERVICESAVEMAPRESPONSE_H
