(cl:in-package ccmslam_msgs-msg)
(cl:export '(BSENTONCE-VAL
          BSENTONCE
          MNID-VAL
          MNID
          MCLIENTID-VAL
          MCLIENTID
          MUNIQUEID-VAL
          MUNIQUEID
          DTIMESTAMP-VAL
          DTIMESTAMP
          MBACK-VAL
          MBACK
          MNGRIDCOLS-VAL
          MNGRIDCOLS
          MNGRIDROWS-VAL
          MNGRIDROWS
          MFGRIDELEMENTWIDTHINV-VAL
          MFGRIDELEMENTWIDTHINV
          MFGRIDELEMENTHEIGHTINV-VAL
          MFGRIDELEMENTHEIGHTINV
          FX-VAL
          FX
          FY-VAL
          FY
          CX-VAL
          CX
          CY-VAL
          CY
          INVFX-VAL
          INVFX
          INVFY-VAL
          INVFY
          N-VAL
          N
          MVKEYSUN-VAL
          MVKEYSUN
          MDESCRIPTORS-VAL
          MDESCRIPTORS
          MTCPRED-VAL
          MTCPRED
          MTCPAR-VAL
          MTCPAR
          MBPOSECHANGED-VAL
          MBPOSECHANGED
          MBSERVERBA-VAL
          MBSERVERBA
          MT_SC-VAL
          MT_SC
          MNSCALELEVELS-VAL
          MNSCALELEVELS
          MFSCALEFACTOR-VAL
          MFSCALEFACTOR
          MFLOGSCALEFACTOR-VAL
          MFLOGSCALEFACTOR
          MVSCALEFACTORS-VAL
          MVSCALEFACTORS
          MVLEVELSIGMA2-VAL
          MVLEVELSIGMA2
          MVINVLEVELSIGMA2-VAL
          MVINVLEVELSIGMA2
          MNMINX-VAL
          MNMINX
          MNMINY-VAL
          MNMINY
          MNMAXX-VAL
          MNMAXX
          MNMAXY-VAL
          MNMAXY
          MK-VAL
          MK
          MVPMAPPOINTS_IDS-VAL
          MVPMAPPOINTS_IDS
          MVPMAPPOINTS_CLIENTIDS-VAL
          MVPMAPPOINTS_CLIENTIDS
          MVPMAPPOINTS_VECTID-VAL
          MVPMAPPOINTS_VECTID
          MPPRED_KFID-VAL
          MPPRED_KFID
          MPPRED_KFCLIENTID-VAL
          MPPRED_KFCLIENTID
          MPPAR_KFID-VAL
          MPPAR_KFID
          MPPAR_KFCLIENTID-VAL
          MPPAR_KFCLIENTID
          MBBAD-VAL
          MBBAD
))