(cl:in-package ccmslam_msgs-msg)
(cl:export '(MNID-VAL
          MNID
          MCLIENTID-VAL
          MCLIENTID
          MUNIQUEID-VAL
          MUNIQUEID
          MBACK-VAL
          MBACK
          MPOSPRED-VAL
          MPOSPRED
          MPOSPAR-VAL
          MPOSPAR
          MBNORMALANDDEPTHCHANGED-VAL
          MBNORMALANDDEPTHCHANGED
          MBSERVERBA-VAL
          MBSERVERBA
          MPPREDKFID-VAL
          MPPREDKFID
          MPPREDKFCLIENTID-VAL
          MPPREDKFCLIENTID
          MPPARKFID-VAL
          MPPARKFID
          MPPARKFCLIENTID-VAL
          MPPARKFCLIENTID
          MBBAD-VAL
          MBBAD
          MBMULTIUSE-VAL
          MBMULTIUSE
))